#!/usr/bin/expect -f

# Copyright (c) 2017 Fabian Wenzelmann

# MIT License
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# This is a wrapper until mlmmj-make-ml is fixed to work in a non-interactive
# mode.
# Currently they seem to be working on it (September 2017), until it is
# really fixed and available this is a simplified script to
# This is a simplified version and does not yet support all options
# from mlmmj-make-ml.
# Will be removed once this is fixed.

# usage: ./mk_ml mlmmj_cmd spool ml_name domain owner lang

set cmd [lindex $argv 0]
set spool [lindex $argv 1]
set mlname [lindex $argv 2]
set domain [lindex $argv 3]
set owner [lindex $argv 4]
set lang [lindex $argv 5]

if {$cmd == "" || $spool == "" | $mlname == "" || $domain == "" || $owner == "" || $lang == ""} {
  puts "Usage: mlmmj_cmd spool ml_name domain owner lang"
  exit 1
}

spawn $cmd -s $spool
expect "What should the name of the Mailinglist be? \\\[mlmmj-test\\\] : "
send "$mlname\r"
expect "The Domain for the List? \\\[\\\] : "
send "$domain\r"
expect "The emailaddress of the list owner? \\\[postmaster\\\] : "
send "$owner\r"
expect "The path to texts for the list? \\\[en\\\] : "
send "$lang\r"
expect eof
